api_platform:
    title: Task Manager
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    show_webby: false
    swagger:
        api_keys:
            Bearer:
                name: Authorization
                type: header
