# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:

        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_DB: app
                    POSTGRES_USER: app
                    POSTGRES_PASSWORD: pass
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -d app -U app"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: mbstring, pdo_pgsql, intl
                    coverage: xdebug

            -   name: Install Composer dependencies
                run: composer update --prefer-dist --no-progress

            -   name: Wait for PostgreSQL to be ready
                run: |
                    for i in {1..10}; do
                      pg_isready -h 127.0.0.1 -p 5432 -U app && break
                      echo "Waiting for PostgreSQL..."
                      sleep 5
                    done

            -   name: Create .env.test.local
                run: |
                    echo "DATABASE_URL=postgresql://app:pass@127.0.0.1:5432/app" > .env.test.local

            -   name: Create database
                run: php bin/console doctrine:database:create --env=test --no-interaction

            -   name: Run Doctrine migrations (optional)
                run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

            -   name: Upload fixtures
                run: php bin/console doctrine:fixtures:load --env=test --no-interaction

                continue-on-error: true

            -   name: Run PHPUnit tests
                run: ./vendor/bin/phpunit --colors=always
